texture:
  title: Franz Wilhelmstötter
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: jeneticsga
    github:  jenetics
    linkedIn: in/franz-wilhelmstötter-949173b
    rss: rss


show_excerpts: true

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

remote_theme: thelehhman/texture
