title: Jenetics' Blog
author: Franz Wilhelmstötter
email: franz.wilhelmstötter@gmail.com
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
#sass:
#  sass_dir: _sass

permalink: /posts/:title/

texture:
  title: Franz Wilhelmstötter
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: jeneticsga
    github:  jenetics
    linkedIn: in/franz-wilhelmstötter-949173b
    rss: rss

plugins:
  - jekyll-seo-tag
  #- jekyll-feed

remote_theme: thelehhman/texture
