texture:
  title: Franz Wilhelmstötter
  tagline: Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: jeneticsga
    github:  jenetics
    linkedIn: in/franz-wilhelmstötter-949173b
    rss: rss


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed

remote_theme: thelehhman/texture
